# Generated by Django 5.1 on 2024-09-25 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cuisine_type", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("rating", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dietary_restrictions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="favorite_cuisine",
            field=models.CharField(
                choices=[
                    ("Italian", "Italian"),
                    ("Chinese", "Chinese"),
                    ("Indian", "Indian"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_restaurants",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="restaurants.restaurant"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("rating", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="restaurants.userprofile",
                    ),
                ),
            ],
        ),
    ]
